name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grants write access for content, including creating releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract version number
        id: extract_version
        run: |
          VERSION=$(grep "BepInPlugin" MainMod.cs | cut -d'"' -f6)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compare version number
        run: |
          echo "Current version: $VERSION"
          LATEST_VERSION=$(git tag -l | sort -V | tail -1)
          echo "Latest tag: $LATEST_VERSION"
          if [ -z "$LATEST_VERSION" ]; then
            echo "No latest tag found"
            echo "New version detected: $VERSION"
          elif [ "$VERSION" != "$LATEST_VERSION" ]; then
            echo "New version detected: $VERSION"
          else
            echo "No new version detected"
            exit 0
          fi
        env:
          VERSION: ${{ env.VERSION }}

      - name: Generate tag name
        run: echo "TAG_NAME=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.VERSION }}"  # Now using only the version number, no "Release" prefix
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
