name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grants write access for content, including creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Set this to your required .NET version

      - name: Extract version number
        id: extract_version
        run: |
          VERSION=$(grep "BepInPlugin" MainMod.cs | cut -d'"' -f6)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compare version number
        run: |
          echo "Current version: $VERSION"
          LATEST_VERSION=$(git tag -l | sort -V | tail -1)
          echo "Latest tag: $LATEST_VERSION"
          if [ -z "$LATEST_VERSION" ]; then
            echo "No latest tag found"
            echo "New version detected: $VERSION"
          elif [ "$VERSION" != "$LATEST_VERSION" ]; then
            echo "New version detected: $VERSION"
          else
            echo "No new version detected"
            exit 0
          fi
        env:
          VERSION: ${{ env.VERSION }}

      - name: Generate tag name
        run: echo "TAG_NAME=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Build the project
        run: |
          dotnet build -c Release  # Builds the project in Release mode
        working-directory: ./  # Ensure it's running in the root of the project

      - name: Upload AmongUsMenu.dll to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ env.VERSION }}"  # Use the version number as release name
          tag_name: ${{ env.TAG_NAME }}
          files: ./bin/Release/net6.0/AmongUsMenu.dll  # Upload the specific DLL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up build output
        run: |
          rm -rf ./bin/Release  # Remove the build folder after uploading the DLL
